name: 定时拉原仓库更新并推 gh-pages
on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 0 * * *' # 每天 0 点执行一次，可按需修改

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/jaywcjlove/reference.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge main branch
        run: |
          git checkout main
          git merge upstream/main --no-edit

      - name: Merge gh-pages branch
        run: |
          git checkout gh-pages
          git merge upstream/gh-pages --no-edit

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
